language: ruby
sudo: false
rvm:
    - stable
env:
    matrix:
        - DB=mysql
        - DB=postgresql
before_script:
    - cp spec/travis/database.travis.yml config/database.yml
    - mysql -e 'create database travis_ci_test'
    - psql -c 'create database travis_ci_test' -U postgres
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - cd spec/dummy
    - RAILS_ENV=test bundle exec rake referrer:install:migrations
    - RAILS_ENV=test bundle exec rails g referrer:tracking Request
    - bundle exec rake db:migrate
    - RAILS_ENV=test bundle exec rails s -d
    - bundle exec rspec
