language: ruby
cache: bundler
sudo: false
rvm:
    - 2.2.2
gemfile:
    - spec/travis/gemfiles/Gemfile-4.2
    - spec/travis/gemfiles/Gemfile-5
env:
    matrix:
        - DB=mysql2
        - DB=postgresql
        - DB=sqlite3
before_script:
    - cp spec/travis/database.travis.yml spec/dummy/config/database.yml
    - mysql -e 'create database travis_ci_test'
    - psql -c 'create database travis_ci_test' -U postgres
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - cd spec/dummy
    - RAILS_ENV=test bundle exec rake referrer:install:migrations
    - bundle exec rake db:migrate
    - RAILS_ENV=test bundle exec rails s -d
    - bundle exec rspec
